### ISSUE TITLE
Equality and hashcodes on collections

### ISSUE THREAD

**Issue by navibyte** [navibyte/dataflow#1]
Most immutable classes uses EquatableMixin from equatable package that helps to implement equality without needing to explicitly override == and hashCode.

For this library these questions apply at least for 
* `DataObject` and `DataObjectView`
* `DataArray` and `DataArrayView`

Analyze how Equatable library works on collections.

See also [built_collection](https://pub.dev/packages/built_collection) for reference about deep comparisions on hash and equals.

**Comment by navibyte** [comment]
Similar open issues on geocore too:
https://github.com/navibyte/geospatial/issues/12

**Comment by navispatial** [comment]
DataObjectView and DataArrayView are defined `with EquatableMixin`

It has deep hash and deep equality.
However calculated hash value is not cached.

DataObjectView and DataArrayView is some case may contain mutable data maps or data lists. So can't cache hash value.

Let's keep implementation as it's now with trusting hashCode and equality checks implemented by EquableMixin.
